import types
from typing import Self

class SockAddr:
    @staticmethod
    def v4(ip: str, port: int) -> SockAddr: ...
    @staticmethod
    def v6(ip: str, port: int) -> SockAddr: ...

class CompletionEvent:
    @property
    def user_data(self) -> int: ...
    @property
    def res(self) -> int: ...
    @property
    def flags(self) -> int: ...

class Ring:
    def __init__(self, depth: int = 32) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> bool: ...
    def submit(self) -> int: ...
    def peek(self) -> CompletionEvent | None: ...
    def wait(self) -> CompletionEvent: ...
    def prep_nop(self, user_data: int) -> None: ...
    def prep_timeout(self, user_data: int, sec: int, nsec: int) -> None: ...
    def prep_close(
        self,
        user_data: int,
        fd: int,
    ) -> None: ...
    def prep_cancel(
        self, user_data: int, target_user_data: int, flags: int = 0
    ) -> None: ...
    def prep_read(
        self, user_data: int, fd: int, buf: bytearray, nbytes: int, offset: int
    ) -> None: ...
    def prep_write(self, user_data: int, fd: int, buf: bytes, offset: int) -> None: ...
    def prep_openat(
        self, user_data: int, path: str, flags: int, mode: int, dir_fd: int
    ) -> None: ...
    def prep_socket(
        self,
        user_data: int,
        domain: int,
        sock_type: int,
        protocol: int = 0,
        flags: int = 0,
    ) -> None: ...
    def prep_socket_setopt(
        self,
        user_data: int,
        fd: int,
    ) -> None: ...
    def prep_socket_bind(
        self, user_data: int, fd: int, sock_addr: SockAddr
    ) -> None: ...
    def prep_socket_listen(self, user_data: int, fd: int, backlog: int) -> None: ...
    def prep_socket_accept(self, user_data: int, fd: int) -> None: ...
    def prep_socket_recv(
        self, user_data: int, fd: int, buf: bytearray, flags: int = 0
    ) -> None: ...
    def prep_socket_send(
        self, user_data: int, fd: int, buf: bytes, flags: int = 0
    ) -> None: ...
    def prep_socket_connect(
        self, user_data: int, fd: int, sock_addr: SockAddr
    ) -> None: ...
