import types
from typing import Self

class CompletionEvent:
    @property
    def user_data(self) -> int: ...
    @property
    def res(self) -> int: ...
    @property
    def flags(self) -> int: ...

class Ring:
    def __init__(self, depth: int = 32) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> bool: ...
    def submit(self) -> int: ...
    def peek(self) -> CompletionEvent | None: ...
    def wait(self) -> CompletionEvent: ...
    def prep_nop(self, user_data: int) -> None: ...
    def prep_read(
        self, user_data: int, fd: int, buf: bytearray, nbytes: int, offset: int
    ) -> None: ...
    def prep_write(
        self, user_data: int, fd: int, buf: bytearray, nbytes: int, offset: int
    ) -> None: ...
    def prep_openat(
        self, user_data: int, path: str, flags: int, mode: int, dir_fd: int
    ) -> None: ...
